M48
; DRILL file {KiCad (6.0.9-0)} date Tuesday, November 15, 2022 at 09:04:57 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-15T21:04:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.85Y-0.8
X0.85Y-4.35
X9.4Y-0.8
X9.4Y-4.35
T0
M30
